2020-12-02 00:01:11 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:01:11 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:01:25 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:01:25 [INFO] : --------------------------------------------
2020-12-02 00:12:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:12:33 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:12:55 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:12:55 [INFO] : --------------------------------------------
2020-12-02 00:16:20 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:16:20 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:17:03 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:17:03 [INFO] : --------------------------------------------
2020-12-02 00:17:54 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:17:54 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:17:57 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:17:57 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:17:57 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:17:57 [INFO] : --------------------------------------------
2020-12-02 00:18:21 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:18:21 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:18:27 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:18:27 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:18:27 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:18:27 [INFO] : --------------------------------------------
2020-12-02 00:18:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:18:58 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:19:03 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:19:03 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:19:03 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:19:03 [INFO] : --------------------------------------------
2020-12-02 00:19:14 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:19:14 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:19:21 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:19:21 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 71, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 89, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:19:21 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:19:21 [INFO] : --------------------------------------------
2020-12-02 00:33:38 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:33:38 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:34:23 [INFO] : 得到 [CNVD] 最新威胁情报 [13] 条
2020-12-02 00:34:23 [INFO] : --------------------------------------------
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59313）
[ TIME  ] 2020-10-18 00:33:39
[ CVE   ] CNVD-2020-59313
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59313
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59314）
[ TIME  ] 2020-10-18 00:33:41
[ CVE   ] CNVD-2020-59314
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59314
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59315）
[ TIME  ] 2020-10-18 00:33:43
[ CVE   ] CNVD-2020-59315
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59315
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59398）
[ TIME  ] 2020-10-18 00:33:45
[ CVE   ] CNVD-2020-59398
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59398
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59399）
[ TIME  ] 2020-10-18 00:33:47
[ CVE   ] CNVD-2020-59399
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59399
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59400）
[ TIME  ] 2020-10-18 00:33:49
[ CVE   ] CNVD-2020-59400
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59400
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59401）
[ TIME  ] 2020-10-18 00:33:51
[ CVE   ] CNVD-2020-59401
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59401
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59402）
[ TIME  ] 2020-10-18 00:33:54
[ CVE   ] CNVD-2020-59402
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59402
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59403）
[ TIME  ] 2020-10-18 00:33:56
[ CVE   ] CNVD-2020-59403
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59403
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59404）
[ TIME  ] 2020-10-18 00:33:58
[ CVE   ] CNVD-2020-59404
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59404
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59406）
[ TIME  ] 2020-10-18 00:34:02
[ CVE   ] CNVD-2020-59406
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59406
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59409）
[ TIME  ] 2020-10-18 00:34:09
[ CVE   ] CNVD-2020-59409
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59409
2020-12-02 00:34:23 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞
[ TIME  ] 2020-10-18 00:34:17
[ CVE   ] CNVD-2020-59413
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59413
2020-12-02 00:39:23 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:39:23 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:39:26 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 72, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 102, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:39:26 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 72, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 102, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 72, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 102, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:39:26 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:39:26 [INFO] : --------------------------------------------
2020-12-02 00:39:44 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:39:44 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:39:49 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 59, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 73, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 103, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:39:49 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 59, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 73, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 103, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 59, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 73, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 103, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:39:49 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:39:49 [INFO] : --------------------------------------------
2020-12-02 00:42:04 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:42:04 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:42:46 [INFO] : 得到 [CNVD] 最新威胁情报 [1] 条
2020-12-02 00:42:46 [INFO] : --------------------------------------------
2020-12-02 00:42:46 [INFO] : 
==============================================
[ TITLE ] ZZCMS存在文件上传漏洞（CNVD-2020-59410）
[ TIME  ] 2020-10-18 00:42:36
[ CVE   ] CNVD-2020-59410
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59410
2020-12-02 00:44:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:44:58 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:45:40 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:45:40 [INFO] : --------------------------------------------
2020-12-02 00:48:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:48:12 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:48:21 [ERROR] : 获取 [CNVD] 威胁情报异常
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 73, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 101, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:48:21 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 73, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 101, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\crawler\_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 58, in get_cves
    cve = self.to_cve(id)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 73, in to_cve
    self.get_cve_info(cve, cve.url)
  File "D:\workspace\Github\threat-broadcast\src\crawler\cnvd.py", line 101, in get_cve_info
    time.sleep(2)
KeyboardInterrupt
2020-12-02 00:48:21 [INFO] : 得到 [CNVD] 最新威胁情报 [0] 条
2020-12-02 00:48:21 [INFO] : --------------------------------------------
2020-12-02 00:49:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 00:49:58 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 00:50:42 [INFO] : 得到 [CNVD] 最新威胁情报 [13] 条
2020-12-02 00:50:42 [INFO] : --------------------------------------------
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59313）
[ TIME  ] 2020-10-18 00:49:59
[ CVE   ] CNVD-2020-59313
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59313
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59314）
[ TIME  ] 2020-10-18 00:50:01
[ CVE   ] CNVD-2020-59314
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59314
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59315）
[ TIME  ] 2020-10-18 00:50:03
[ CVE   ] CNVD-2020-59315
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59315
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59398）
[ TIME  ] 2020-10-18 00:50:05
[ CVE   ] CNVD-2020-59398
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59398
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59399）
[ TIME  ] 2020-10-18 00:50:07
[ CVE   ] CNVD-2020-59399
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59399
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59400）
[ TIME  ] 2020-10-18 00:50:09
[ CVE   ] CNVD-2020-59400
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59400
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59401）
[ TIME  ] 2020-10-18 00:50:11
[ CVE   ] CNVD-2020-59401
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59401
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59402）
[ TIME  ] 2020-10-18 00:50:13
[ CVE   ] CNVD-2020-59402
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59402
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59403）
[ TIME  ] 2020-10-18 00:50:15
[ CVE   ] CNVD-2020-59403
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59403
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59404）
[ TIME  ] 2020-10-18 00:50:17
[ CVE   ] CNVD-2020-59404
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59404
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59406）
[ TIME  ] 2020-10-18 00:50:22
[ CVE   ] CNVD-2020-59406
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59406
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS存在文件上传漏洞（CNVD-2020-59410）
[ TIME  ] 2020-10-18 00:50:30
[ CVE   ] CNVD-2020-59410
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59410
2020-12-02 00:50:42 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞
[ TIME  ] 2020-10-18 00:50:37
[ CVE   ] CNVD-2020-59413
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59413
2020-12-02 08:58:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2020-12-02 08:58:33 [INFO] : 正在获取 [CNVD] 威胁情报...
2020-12-02 08:59:19 [INFO] : 得到 [CNVD] 最新威胁情报 [13] 条
2020-12-02 08:59:19 [INFO] : --------------------------------------------
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59313）
[ TIME  ] 2020-12-02 08:58:36
[ CVE   ] CNVD-2020-59313
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59313
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59314）
[ TIME  ] 2020-12-02 08:58:38
[ CVE   ] CNVD-2020-59314
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59314
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59315）
[ TIME  ] 2020-12-02 08:58:40
[ CVE   ] CNVD-2020-59315
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59315
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59398）
[ TIME  ] 2020-12-02 08:58:42
[ CVE   ] CNVD-2020-59398
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59398
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59399）
[ TIME  ] 2020-12-02 08:58:44
[ CVE   ] CNVD-2020-59399
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59399
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59400）
[ TIME  ] 2020-12-02 08:58:46
[ CVE   ] CNVD-2020-59400
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59400
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59401）
[ TIME  ] 2020-12-02 08:58:48
[ CVE   ] CNVD-2020-59401
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59401
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59402）
[ TIME  ] 2020-12-02 08:58:50
[ CVE   ] CNVD-2020-59402
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59402
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59403）
[ TIME  ] 2020-12-02 08:58:52
[ CVE   ] CNVD-2020-59403
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59403
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59404）
[ TIME  ] 2020-12-02 08:58:54
[ CVE   ] CNVD-2020-59404
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59404
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS2020后台存在SQL注入漏洞（CNVD-2020-59405）
[ TIME  ] 2020-12-02 08:58:56
[ CVE   ] CNVD-2020-59405
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59405
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] ZZCMS前台存在SQL注入漏洞（CNVD-2020-59408）
[ TIME  ] 2020-12-02 08:59:03
[ CVE   ] CNVD-2020-59408
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-59408
2020-12-02 08:59:19 [INFO] : 
==============================================
[ TITLE ] 闪灵企业建站系统前台存在命令执行漏洞
[ TIME  ] 2020-12-02 08:59:11
[ CVE   ] CNVD-2020-62441
[ SRC   ] CNVD
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2020-62441
2020-12-02 08:59:19 [INFO] : [邮件] 正在推送威胁情报...
2020-12-02 08:59:19 [INFO] : [邮件] 收件人清单： ['threatbroadcast@foxmail.com', '15817830405@139.com']
2020-12-02 08:59:19 [ERROR] : [邮件] 推送威胁情报失败
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\notice\mail.py", line 47, in to_mail
    smtpObj.login(sender, password)
  File "S:\04_work\python\python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "S:\04_work\python\python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "S:\04_work\python\python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (502, b'Invalid input from 100.107.4.33 to newxmesmtplogicsvrszb5.qq.com')
2020-12-02 08:59:19 [ERROR] : Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\notice\mail.py", line 47, in to_mail
    smtpObj.login(sender, password)
  File "S:\04_work\python\python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "S:\04_work\python\python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "S:\04_work\python\python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (502, b'Invalid input from 100.107.4.33 to newxmesmtplogicsvrszb5.qq.com')
Traceback (most recent call last):
  File "D:\workspace\Github\threat-broadcast\src\notice\mail.py", line 47, in to_mail
    smtpObj.login(sender, password)
  File "S:\04_work\python\python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "S:\04_work\python\python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "S:\04_work\python\python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (502, b'Invalid input from 100.107.4.33 to newxmesmtplogicsvrszb5.qq.com')
